### ISSUE TITLE
Validation utilities for schema annotations

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/deriva-py#126]
This issue proposes a new utility (API and CLI) for validating schema annotations. The aim of the utility is to validate the correctness of schema annotations against the annotation spec (i.e., the schema of the schema annotation) and secondly to validate  correctness with respect to the catalog schema (i.e., the ERM).

To validate the correctness of the annotations against their definitions (their schemas), using JSON Schema [1] seems to be the obvious choice. Multiple python implementations of JSON Schema exist with "jsonschema" [2] apparently the most popular and perhaps most mature of them. Initial evaluation using jsonschema with a first cut of a JSON Schema for the `visible-columns` annotations appears promising.

To validate the correctness of the annotations against the catalog schema, the utility will look within certain annotations (e.g., visible columns, source definitions, etc.) for `source` (_sourceentry_) definitions and attempt to deserialize them into `DataPath` instances.

Proposed changes:
- `deriva.core.annotations`: a new module for annotations;
- `deriva.core.annotations.schemas`: a package data directory for containing all known annotation schemas;
- `validate(modelobj, tagname=None)`: a utility function for validating the annotation(s) of an arbitrary model object, with option to restrict the validation to a particular tag name (string) defined in the `tag` variable;
- `test_annotations`: a module of unit tests for the annotation validation routines.
- grafting of the `validate` method onto the `ermrest_model` Class definitions;
- `deriva-annotation-validate`: CLI to validate one/some/all model objects and one/some/all known annotations.

[1] https://json-schema.org/
[2] https://pypi.org/project/jsonschema/

**Comment by karlcz** [comment]
Would it make more sense to integrate this into the `ermrest_model`
class hierarchy as utility methods on the various model nodes?  E.g. a
table instance can evaluate a table-level annotation against "itself"
and its other connected model elements as needed. And the same for
a schema, column, or foreign key node...

If this were tied into the node.annotations setter, it could validate
and raise exceptions to block setting of a bad annotation.  However,
there would be various awkward error scenarios to consider:

1. A retrieved model already has "bad" annotations. We should not
   reject such a model, but we might need a different way to retrieve
   errors or warnings on the existing annotations.

2. Bulk annotations have interdependencies. Annotations cannot be
   validated against local model until after sibling annotations are
   set, e.g. source-definitions and visible-columns using "sourcekey"
   feature could be set in same bulk annotation update.

3. A model input has interdependencies. Annotations cannot be
   validated against local model until after the model changes are
   made, i.e. adding new table+columns+fkeys.

4. The evaluating client is not "owner" of the whole catalog and so
   may be seeing a filtered view of model, causing apparent annotation
   conflicts which are actually normal, expected behavior.

**Comment by robes** [comment]
Sure, it could be integrated with `ermrest_model` class hierarchy if you think that's a better fit than the `ermrest_config` class hierarchy.

I agree with your other comments, especially that we shouldn't restrict invalid annotation setting since we know we have some non-conforming ones.

**Comment by karlcz** [comment]
We have a long-deferred intention to deprecate the ermrest config module entirely.  This reminds me that the branch with refactoring for that (pruneconfig) hasn't been getting patched with master changes in a while now. :-/

**Comment by robes** [comment]
Ah, I forgot about that. (To the point that recently I was wondering what this `pruneconfig` branch was all about :)).

**Comment by robes** [comment]
@karlcz so I'm rethinking my proposed changes in the description. this may be compact enough for me to just add a few methods and supporting functions in `ermrest_model` after the `pruneconfig` PR is merged. and of course another module for the CLI. and also of course the pkg data for the json-schema files themselves. just FYI.

**Comment by robes** [comment]
I'm thinking of a method signature like this to be added to all relevant classes of in the `ermrest_model` module:

```python
def validate(self, tag_name=None, recursive=False):
    """Validates the annotations for this model object.
    
    :param tag_name: tag name of the annotation to validate, if none, will validate all known annotations
    :param recursive: validate annotations of this object and all child objects, if true
    :return: a list of validation errors, if any
    """
```
