### ISSUE TITLE
deriva-hatrac-cli won't download versioned files

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/deriva-py#130]
It looks like an issue with url-encoding the `:`.

Here's a failed deriva-hatrac-cli request:
```
rbk-dev::laura[/var/scratch/image-dev/junk] deriva-hatrac-cli --host www.gudmap.org get /hatrac/resources/histological_images/2018/8704e2901b4fdff29dac639f1faffba7:3ZNEH622LTOZA5S24DD4DVONYM
deriva-hatrac-cli get: /hatrac/resources/histological_images/2018/8704e2901b4fdff29dac639f1faffba7:3ZNEH622LTOZA5S24DD4DVONYM: No such object

Jul  8 19:18:38 www.rebuildingakidney.org hatrac[1274333.140237441156864]: {"elapsed":0.002594, "req":"nPlE33QLjMY=", "trace":"Resource /hatrac/resources/histological_images/2018/8704e2901b4fdff29dac639f1faffba7:3ZNEH622LTOZA5S24DD4DVONYM not found.", "client":"128.9.128.222"}
Jul  8 19:18:38 www.rebuildingakidney.org hatrac[1274333.140237441156864]: {"elapsed":0.003234, "req":"nPlE33QLjMY=", "scheme":"https", "host":"www.gudmap.org", "status":"404 Not Found", "method":"GET", "path":"/hatrac/resources/histological_images/2018/8704e2901b4fdff29dac639f1faffba7%3A3ZNEH622LTOZA5S24DD4DVONYM", "type":"text/plain", "client":"128.9.128.222", "agent":"python-requests/2.23.0", "dcctx":{"cid":"deriva-hatrac-cli", "wid":"9cec30a0f8284c7387cf3008ac318254"}}
```

And here's the equivalent (successful) request with curl:
```
curl https://www.gudmap.org/hatrac/resources/histological_images/2018/8704e2901b4fdff29dac639f1faffba7:3ZNEH622LTOZA5S24DD4DVONYM

Jul  8 19:18:01 www.rebuildingakidney.org hatrac[1274333.140237457942272]: {"elapsed":0.006882, "req":"0AdIm4t82UM=", "scheme":"https", "host":"www.gudmap.org", "status":"200 OK", "method":"GET", "path":"/hatrac/resources/histological_images/2018/8704e2901b4fdff29dac639f1faffba7:3ZNEH622LTOZA5S24DD4DVONYM", "range":"*/202641952", "client":"128.9.128.222", "agent":"curl/7.66.0"}
```

**Comment by robes** [comment]
@ljpearlman Currently, hatrac-cli is urlquoting the path argument with `/` as a safe character. Unfortunately this also means that a valid object name with `%2F` in it (encoded `/`) is also unsupported by the current interface.

I think maybe the right fix here is simply to stop url quoting the path argument and make the user url quote if they use reserved characters in any of their object names. Unless there are any objections.

**Comment by karlcz** [comment]
That makes the most sense to me. So the CLI takes a URL path to a
hatrac resource (namespace, object, object-version) and operates on it
as a whole to pass through to HTTP. Always pass these valid URL
strings in/out, and don't invite misadventure where things get
decoded/reencoded/mangled through naive manipulation.

Once you require the canonical URL path to be passed in, you can do
very minimal substring tests to categorize them appopriately for CLI
validation and error-handling:

1. without ':' or ';': namespace or unqualified object
   - Need to ask hatrac which it is
2. with ':' but not ';': version-qualified object
   - Need to check hatrac for existence
3. with ';': one of the special sub-resource APIs
   - Parent resource could be namespace, object, or object-version
   - Need to consider case-by-case whether CLI support makes sense?

Those special metachars should never appear in a namespace parent
path without already being encoded. However, some sub-resources
include additional '/' path separation so you would want to test
the whole path string rather than splitting on '/' and then only
testing the right-most section of the path!

**Comment by robes** [comment]
OK. Good.

Currently, it already supports the ACL subresource through some APIs that I had also added to the HatracStore API. So the CLI takes the resource name and separately takes the ACL name and Role(s) and then constructs the Hatrac path using those parts.

The funny thing about this change is that one could implicitly fetch the ACL resource through what was intended to be an object fetch `deriva-hatrac-cli get <resourcename>`.

So maybe to make this complete I should at least do your test cases above for the validation and error handling?

**Comment by ljpearlman** [comment]
Another option would be to take a similar approach to what you're doing with ACL requests, and provide for a separate "version" argument that you could use to construct hatrac paths for those operations for which that makes sense. I'm not sure which method I like better, actually, but I thought I'd throw this out there as an option.

**Comment by ljpearlman** [comment]
Oh, I  see you've already made the change. Never mind.

**Comment by robes** [comment]
Yeah, the problem with having a version option is that it doesn't resolve the issue of the naive encoding of `/` so it seems like just not encoding is the best option available. I don't mind adding a version option (`--object-version ###`) if that would help.

**Comment by ljpearlman** [comment]
I don't think we need the extra option, thanks.

**Comment by karlcz** [comment]
I think it comes down to expected use...  Why would you have a version
string that isn't already part of a well-formed URL path?  I assume it
is because you encountered it in an ermrest record or similar, and so
you'd want to just pass the full string, not mess around with
splitting it into separate arguments.

Also, the ';versions' sub-resource only works for the "owner" privilege
level, so it wouldn't work in the general case to provide a version
discovery sub-command in the CLI.  You can try to get the latest version,
or a prior version you already know by exact reference, but not ask for
a menu of version options.

**Comment by robes** [comment]
That all makes sense to me.
