### ISSUE TITLE
Hatrac_Store.put_loc() raises "Current uploaded content MD5 does not match the expected one"

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/deriva-py#142]
[panTro3_C_I_32_RST_1.6x.txt](https://github.com/informatics-isi-edu/deriva-py/files/6209387/panTro3_C_I_32_RST_1.6x.txt)

The attached file has only `914` bytes.
The code I am using:
```
hatrac_store = HatracStore(
    'https', 
    hostname,
    {'cookie': cookie}
)
file_name = 'panTro3_C_I_32_RST_1.6x.txt'
hashes = hu.compute_file_hashes(file_name, hashes=['md5', 'sha256'])
md5 = hashes['md5'][1]
sha256 = hashes['sha256'][1]
url= '/hatrac/resources/gene_expression/processed_images/2021/03/17-3TSY/panTro3_C_I_32_RST_1.6x.txt'

if mimetypes.inited == False:
    mimetypes.init()
content_type,encoding = mimetypes.guess_type(args.file)
if content_type == None:
    content_type = 'application/octet-stream'
hatrac_URI = hatrac_store.put_loc(url,
                                     file_name,
                                     headers={'Content-Type': content_type},
                                     content_disposition = "filename*=UTF-8''%s" % urlquote(file_name),
                                     md5 = md5,
                                     sha256 = sha256,
                                     content_type = content_type,
                                     chunked = True
                                   )
```
The exception I am getting:
```
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: [https://dev.facebase.org/hatrac/facebase/data/fb3/VP4/39DY/proc_img/3KWA/panTro3_C_I_32_RST_1.6x.txt;upload/XA5ABTRDG2IW4HTU62RAJZ6S54] Details: b"Current uploaded content MD5 b'd41d8cd98f00b204e9800998ecf8427e' does not match expected b'8d97847d92bf31500fef0d772be2eafd'.\n"
```
I tested it on both `dev.facebase.org` and `imaging-dev.gudmap.org`.
From what I can see so far from the logs, the `PUT` chunk request is missing and the file on the hatrac filesystem has `0` bytes.

My same code was working last week.

Inspecting a little bit the `deriva-py/deriva/core/hatrac_store.py` file, I think that line `310`:
```
            chunks = file_size / chunk_size
```
should be:
```
            chunks = file_size // chunk_size
```
Otherwise, in Python3 you are getting a float value.

While enabling the debug logging, I can see the message:
```
2021-03-26 08:27:49,611: INFO <hatrac_store>: File [/home/serban/test/panTro3_C_I_32_RST_1.6x.txt] upload successful. 10.00 MB transferred. Elapsed time: 0:00:00.000142.
```
The value of `10.00 MB` represents the `DEFAULT_CHUNK_SIZE` and not the file size.

Briefly, I think the error comes from line `297`:
```
            self.put_obj_chunked(path, file_path, job_id, chunk_size, callback, cancel_job_on_error)
```
which should be something like:
```
            self.put_obj_chunked(path, file_path, job_id, chunk_size, callback, 0, cancel_job_on_error)
```

**Comment by karlcz** [comment]
Further info from our quick debugging yesterday: the server logs
seem to indicate that the chunked upload is starting a job
and finalizing without sending the single (partial) chunk that
would contain the file content.

I took a quick look at the code and do not see an obvious bug, but
wonder if it is silently failing to run the chunk PUT sequence and
continuing with the finalize rather than aborting.  I see that
there were recent changes to some of the exception-handling and
callback code in the relevant functions in deriva-py...

**Comment by mikedarcy** [comment]
I've pushed the fixes for this to master. However, I would also note that using chunked upload for small files is inherently inefficient. I would recommend that per-file, you call `os.path.getsize(file_path)` and test that it is `< DEFAULT_CHUNK_SIZE` (or your override chunk size, if set), and if `true`, simply set `chunked=False` on the call to `put_loc` so that it uses the idempotent 1-shot `put_obj` API instead. That's one REST call vs. three and all of the associated DB overhead of chunked upload jobs.

**Comment by karlcz** [comment]
FWIW, in the Chaise uploader we always use upload jobs because it
gives us a cleaner way to prepare a batch:

1. create all jobs (multiple files)

2. upload all chunks

3A. finalize all jobs
3B. cancel+delete all jobs

if we run into permission errors during (1), we can purge them and we
haven't wasted time uploading chunks nor causing visible state changes
to the affected objects from the POV of other storage clients.

**Comment by svoinea** [comment]
I have tested and it works as expected.
I have also updated my code with the suggested `chunked = True if file_size > DEFAULT_CHUNK_SIZE else False`.
