### ISSUE TITLE
deriva-download-cli not using env for output_path when output_format is json/csv

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/deriva-py#23]
This is really odd but the output_path does not seem to take the env (returned from the query) to populate the template.

I.e.,
`"output_path": "{accession}/{accession}-RNA-Seq"`

Works if `accession` was passed as a `key=value` CLI argument but not if it was returned from the query.

_Unless_ output_format is fetch or download

**Comment by mikedarcy** [comment]
This is actually part of the current design.  We do no iterate over the bulk tabular data returned as CSV/JSON, for both performance reasons and logical reasons.  For the latter, it is conceivable that multiple rows have different values for the same environment value that is meant to be assigned, so using the current logic would result in a "last value wins" assignment.

Technically it is not really a bug as things stand right now.  We can change this to enhancement and try to come with an option to enable this behavior, but we should try to define the behavior first.

**Comment by robes** [comment]
OK. That makes sense. Although I'm pretty sure iterating over the return data should not be a performance factor as compared to file IO. But okay, if that's the design decision.

**Comment by mikedarcy** [comment]
For performance reasons, we don't process the tabular return data as structured data in memory, it is processed as byte stream in fairly large buffer chunks and written directly to disk as it is consumed from the wire.  We do this to cover cases where the result set could be quite large. So, in order to iterate over it, we basically have to open the file after it is transferred and process it then.

We could possibly introduce a mode where you could specify that the entire result is buffered and then scanned for environment replacement, but this is something that the download config writer/admin would have to set, and would do so assuming the query result was reasonably small.  It still doesn't address the last value variable contention however, so we'd need to come up with something there...

If you are just trying to build up a global environment of variables, maybe we just introduce a new output_format type called _environment_ or somesuch and then you can introduce any number of queries to build up the environment.  In that case, the variable contention would be less of an issue I think, since it would be up to the configuration writer to come up with queries that make sense and don't clobber the environment.

**Comment by robes** [comment]
Not sure that I agree that you'd have to write to disk first before looking at the results stream. Anyway, you have a reason that its not the design so that's fine.

**Comment by mikedarcy** [comment]
We are reading the results in as raw byte-stream chunks with fixed sized buffers that don't necessarily align on any meaningful structured data boundary, not as delimited lines of text. I am not sure we are supposed to determine CSV or JSON structure from that "on-the-fly" without somehow reassembling it all in memory or on disk...

Would my last suggestion about an _environment_ query output type work for your use case?

**Comment by robes** [comment]
I don’t think its necessary. Might be nice to have but not necessary.

**Comment by mikedarcy** [comment]
It was a relatively easy thing to implement. I will add it to the next release.
