### ISSUE TITLE
Support for 'versioned' catalogs

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/deriva-py#27]
Current thinking:
- add a new `ErmrestSnapshot` class as a subclass of `ErmrestCatalog`
- constructor for `ErmrestSnapshot` will take a catalog id and snapshot (string)
- add a `fix()` method to the `ErmrestCatalog` class that gets the current snapshot for the catalog and returns an instance of `ErmrestSnapshot`
- add an optional `snapshot` parameter to the `get_deriva_catalog()` method of the new `DerivaServer` class, which acts as a factory and will return an instance of `ErmrestSnapshot` if the optional `snapshot` parameter is given
- we might also want to parse the catalog_id passed to `get_deriva_catalog()` to _check if its a versioned_ catalog id and if so return the snapshot instance.
- ~also could add a `to be named()` method to `ErmrestSnapshot` to return the unversioned `ErmrestCatalog` instance.~ I'm gonna scratch this off as it only adds a second way to do something that can (will) be done via one of the above new APIs.

What we are not thinking:
- jumping back and forth between versioned and unversioned states of a catalog instance,
- these are big state transitions and the client / user of the API needs to be aware of it.

What we might consider:
- ideally the APIs (even _sub_ APIs) of the `ErmrestSnapshot` should not allow the user to attempt mutation,
- better yet, we could remove mutating methods from those sub-APIs. E.g., the datapath APIs returned from a snapshot should not have `insert`, `update`, and `delete` methods on them.
- however, this isn't necessary strictly speaking because ermrest will return a failure anyway; this is only for convenience.

**Comment by carlkesselman** [comment]
I think this would be very helpful.

So if we wanted to mutate a catalog, we would have to explicitly get a new ErmrestCatalog instance and mutate through that.  I can live with that.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Apr 18, 2018, at 10:55 AM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


Current thinking:

  *   add a new ErmrestSnapshot class as a subclass of ErmrestCatalog
  *   constructor for ErmrestSnapshot will take a catalog id and snapshot (string)
  *   add a fix() method to the ErmrestCatalog class that gets the current snapshot for the catalog and returns an instance of ErmrestSnapshot
  *   add an optional snapshot parameter to the get_deriva_catalog() method of the new DerivaServer class, which acts as a factory and will return an instance of ErmrestSnapshot if the optional snapshot parameter is given
  *   we might also want to parse the catalog_id passed to get_deriva_catalog() to check if its a versioned catalog id and if so return the snapshot instance.
  *   also could add a to be named() method to ErmrestSnapshot to return the unversioned ErmrestCatalog instance.

What we are not thinking:

  *   jumping back and forth between versioned and unversioned states of a catalog instance,
  *   these are big state transitions and the client / user of the API needs to be aware of it.

What we might consider:

  *   ideally the APIs (even sub APIs) of the ErmrestSnapshot should not allow the user to attempt mutation,
  *   better yet, we could remove mutating methods from those sub-APIs. E.g., the datapath APIs returned from a snapshot should not have insert, update, and delete methods on them.
  *   however, this isn't necessary strictly speaking because ermrest will return a failure anyway; this is only for convenience.

**Comment by karlcz** [comment]
This was merged long ago, so I think this issue is just stale.
