### ISSUE TITLE
Setter for column_display annotation doesn't work.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/deriva-py#42]
It is not possible to set a column display annotation via deriva-py

**Comment by karlcz** [comment]
Like all the other built-in properties exposing annotation tags which are expected to contain an object, it doesn't currently have a setter. Rather, it is a lazy property that idempotently creates and returns a dictionary you can mutate.   Idiomatic usage:

`column.column_display["*"] = {"column_order": False}`

This property is really just a thin syntactic sugar for a common idiom you would otherwise have to do on
annotation storage when building up configs:

```
# idiomatic syntactic sugar
column.column_display["*"] = foo

# equivalent to preceding sugar
if tag.column_display not in column.annotations:
    column.annotations[tag.column_display] = dict()
column.annotations[tag.column_display]["*"] = foo
```
Once you want to do more general manipulation, the generic access is more concise:

```
# clumsy sugar approximating a setter
column.column_display.clear() # drop any existing content
column.column_display.update(doc) # write new config document

# direct setting
column.annotations[tag.column_display] = doc # implicitly discards previous document (if any)
```

On the other hand, the sugar is concise for merging changes without worrying about the previous state:

```
# sugar for idempotent create-or-merge
column.column_display.update(merge_doc)

# equivalent to preceding sugar
if tag.column_display not in column.annotations:
    column.annotations[tag.column_display] = dict()
column.annotations[tag.column_display].update(merge_doc)
```

I'm not sure we should keep adding more baroque getter/setter/deleter property behaviors. I'm not sure we should be trying to insulate the caller from the generic semantics of the annotation store...  @robes @ljpearlman @mikedarcy

**Comment by carlkesselman** [comment]
How is any user supposed to understand how to use this?  We need consistent, simple behavior and this needs to be documented somewhere.

**Comment by karlcz** [comment]
The changes in PR #49  makes these convenience annotation interfaces more complete and consistent to have setter (and deleter) behaviors as well as the idempotent initialization when using the getter, as before.

**Comment by karlcz** [comment]
The PR was merged.
