### ISSUE TITLE
Access to comments on schema and catalog

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/deriva-py#50]
It is not currently possible to set or access comments on the schema or catalog objects.  For consistency, I would think that this should be possible.

**Comment by karlcz** [comment]
There are no comments on catalogs in ermrest and hence no support in deriva-py either.

There are comments in schemas in both ermrest and deriva-py.  On a schema object you can assign to `sobj.comment` and like annotations it will be pushed to the remote catalog when you do `model.apply()`.

I am closing this because I think you just tripped on the catalog.comment interface being unavailable and assumed it was also the case for schemas.  If you have problems for schema.comment as well, please reopen...
