### ISSUE TITLE
BaseCLI host argument is optional

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/deriva-py#58]
Right now the host argument is optional.  I would propose we at least add an option to the init of BaseCLI that would add required=True to the host option as I would think this is a very common use case.

**Comment by mikedarcy** [comment]
If an argument is _required_ it is general convention to just make it a positional argument rather than an  option with the required flag set. This tends to ensure options stay _optional_.

Certainly, an initialization parameter can be added to the BaseCLI constructor to make `host` a required positional argument rather than an option. 

It can also be accomplished with the existing code (which we already do in some CLIs) by doing the following in the constructor of derived classes, after the initialization of the base class:

```
        self.remove_options(['--host'])
        self.parser.add_argument('host', metavar='<host>', help="Fully qualified host name.")
```

**Comment by carlkesselman** [comment]
I am fine with making it required.  My overall question is that hostname seems to me to be pretty much a universal argument to any command line tool but we are making it optional.

Carl

Sent from my iPhone

On Feb 26, 2019, at 7:05 PM, mikedarcy <notifications@github.com<mailto:notifications@github.com>> wrote:


If an argument is required it is general convention to just make it a positional argument rather than an option with the required flag set. This tends to ensure options stay optional.

Certainly, an initialization parameter can be added to the BaseCLI constructor to make host a required positional argument rather than an option.

It can also be accomplished with the existing code (which we already do in some CLIs) by doing the following in the constructor of derived classes, after the initialization of the base class:

        self.remove_options(['--host'])
        self.parser.add_argument('host', metavar='<host>', help="Fully qualified host name.")

**Comment by mikedarcy** [comment]
When the `BaseCLI` class was first written it was not clear that the general usage pattern of derived classes was going to include some kind of interaction with a server, so the intention was not to have a required `host` argument for CLIs that only operated "locally".  As it turns out, the latter usage pattern is far less common; therefore we should change things around so that by default, `host` is always the first required positional argument, unless explicitly disabled via a constructor flag.

**Comment by mikedarcy** [comment]
For backward compatibility, this has been implemented so that by passing `hostname_required=True` as an `__init__` argument to the BaseCLI superclass, one can force `host` to be a required positional (the first) argument.
